Add missing multi-line separator
Otherwise this fails to build ( found on mips )

Fixes
contrib/modules/surface_matching/src/hash_murmur86.hpp:97:15: error:
expected constructor, destructor, or type conversion before '(' token
     && defined(__GNUC__) && (__GNUC__>4 || (__GNUC__==4 &&
__GNUC_MINOR__>=3))
               ^