Fuzzy module added
fixes

fixed compile error and warning

Remove AGAST (for merger to upstream opencv)

wrapping remaining xfeature2d classes to scripting

added test for http://code.opencv.org/issues/3943;
replaced "const InputArray" with "InputArray" to avoid warnings about "const const _InputArray&"

added test for http://code.opencv.org/issues/3943;
replaced "const InputArray" with "InputArray" to avoid warnings about "const const _InputArray&"

adding LATCH

fixed warnings in LATCH

fixed errors

fixed warnings

fixed warnings2

fixed warnings3

fixed warnings4

fixed warnings5

added description of LATCH and fixed indentation

cleaned the code a bit

added tests and renamed LATCH

Code to grab the red lined polygon from Google Maps

added python support and completed documentation

figure update

added stdout welcome message and fixed warning

fixed warning

text enhancement

trying to fix python wrapper warning on win64

trying to solve pyhton warnings

bugfix4269 included remarks in http://answers.opencv.org/question/59293/problem-with-example-motemplcpp/

Replace tab with four space

Add rotation invariance option for BRIEF descriptor.

Fix docs and repush for buildbot.

Bug fix for feature extraction

According to CartToPolar() function documentation, result angles could be in range (0..360). To prevent index overflow this check is important.

Adding edge-aware disparity filtering

Added basic interface and demo for disparity filtering, added unoptimized fast weighted least
squares filter implementation. Current demo tests domain transform, guided and
weighted least squares filters on a dataset, measures speed and quality.

Fix for Bug 4074. This seems to be just a typo-error, because the Tesseract API can handle correctly with RGB images (double-checked and it works).

Fix for Bug #3633: do away with "quads [2][3] = 255;" The four lowest bits in each quads[i][j] correspond to the 2x2 binary patterns Q_1, Q_2, Q_3 in the NM paper [1] (see in page 4 at the end of first column). Q_1 and Q_2 have four patterns, while Q_3 has only two.

added INRIA pedestrian dataset

autowbGrayworld: include+src+test+testdata+sample

Add saturation based thresholding to grayworld WB

Add basic perf tests for grayworld

Add more doxygen comments

Suppress uchar conv related warning on Windows

Apply fixes suggested by Vadim

Be more correct with int types

Remove dangling N_good++

Use cvRound to suppress Windows warnings

remove floor call

vs2010 does not know, ceil, floor, round and friends.

also, those are plain integer divisions, that do not need floor at all.

New stereo module created and added some relevant files for this module

Update README.md

made some extra changes to the modules so I receive no warnings

moved the opencv2/core/private.hpp from stereo_binary_sgbm.cpp to precomp.hpp

fix for issue #195

avoid overflow in histogram access

SurfaceMatching: OpenMP indices

Fixes compiler error: "index variable in OpenMP 'for' statement must have signed integral type"

Adding confidence support and optimizing disparity filtering

DisparityWLSFilter demonstrated the best results, so I removed all the other
filters. Quality was significantly improved by adding confidence support
to the filter (left-right consistency + penalty for areas near depth discontinuities).
Filter was optimized using parallel_for_ and HAL intrinsics. Demo application was
rewritten for better compliance with OpenCV standards. Added accuracy and
performance tests. Documentation was added, as well as references to the
original papers.

added PASCAL VOC dataset

+ add KCF Tracker, initial commit, added: tutorial, trackerKCF.cpp, modified: tracker.cpp, tracker.hpp

adding the resize feature

References for KCF tracker and KCF-CN  tracker

Unified the formatting

Fixed: ROI extraction when the given ROI is out of image; made the max_patch_size to be adjustable; add the CN feature extraction method

Removing all shadowing variables, make functions to const, make the table of color-names become static

change the color-names table to const

Add a framework for choosing the descriptor

Added error message for descriptor other than GRAY

Added new line at end of file

Fixing the ColorNames table initialization

Fixed warning: conversion from double to int

Updated the support for color-names features and fixing some typos

Fixing the tabulation

Split the training coefficient into numerator and denumerator

Added the feature compression method

Fixing some indentations

Fixing some indentations

Fixing alignments

Fixing some alignments

Use Doxigen format

Remove whitespaces

Removing whitespaces in featureColorName.cpp

Add an example code for the KCF tracker

update the header in example/kcf.cpp

Updating the rectangle drawing, avoid warning from variable conversion

Added doxygen documentations

Fixing warnings

remove warnings

Fixing some warnings

TLD Fixes & Optimizations

1. TLD now have module structure
2. Made some small code optimizations
3. Fixed Ensemble Classifier according to the original paper - 10
randomized ferns
4. Added comments to most of the functions and methods

Added test on TLD Dataset

Added BSD-compatible license

Added BSD-compatible license to some files

Fixed header

Fixed build error

Fix

Fix #2

Fix #3

Fix #4

Fixed Warnings #1

Fixed Warnings #2

Fixed Warnings #3

Shadow Fix

Fixing whitespaces

Fixing whitespaces #2

Fixing whitespaces #3

Adds a first implementation of the OCRBeamSearchDecoder class using the Single Layer CNN character classifier described in Coates, Adam, et al. paper: Text detection and character recognition in scene images with unsupervised feature learning, ICDAR 2011

Add a demo program for the OCRBeamSearchDecoder class and needed data files

trailing whitespaces

fix compilation warnings

fix win64 compilation error: arrays must be defined with compile-time fixed size :)

fix doxygen warnings

Fix for https://github.com/Itseez/opencv_contrib/issues/278 - core dump in the case of no match results.

Modified reported poses by constraining to the number of poses found.

ulong -> size_t

fixed warnings in the tracking module

Added OCL versions of Sr and Sc functions

2-nd level of parallelization + detector remake

1. Added 2-nd level of parallelization of NN on OpenCL
2. Restructured detector - now all filters work independently:
Variance Filter->Ensemble->NN,  through "buffers"

Warnings Fix #1

Fixing Warnings #2

Fixing Warnings #3

Fixing Warnings #4

Fixing Warnings #5

Fixing Warnings #3

Fixing Warnings #4

Fixing Warnings #5

Added OCL version of "integrateAdditional" function

Whitespace Fix

Transparent API Support

Fixing Warnings

Fixed bug in LSDDetector where mask doesn't remove all undesired lines

Fixing GCC 4.9 warning

Fix memory leak bug #4420

Fix bug #4373: Error (Assertion failed in resize) when passing very elongated contours to the recognition module

make sources compile again on MSVC 2012 (VC 11) by adding round()

fix suffix that was in-compatible with MSVC 2012 (VC 11)

eliminate some warnings

use better condition for checking if compiler supports round()

fixing facerecognizer tutorials and interface

Adds createOCRHMMTransitionsTable() utility function to create a tailored language model transitions table from a given list of words (lexicon)

update to use the new createOCRHMMTransitionsTable() function, and fix program description in header comments

fix Winx64 warnings

Better CNN model for character recognition. Trained with an augmented dataset by adding translation/scale variations. Updated the croped word recognition with new class numbering (compatible with previous NM classifier).

Overload the run() method in BaseOCR class in order to adapt to different classifier callbacks. The original run() method accepts only one Mat input image, this is expected to be a binarzed image with black and white text and works both with the OCRTesseract class and the OCRHMMDecoder class when the character classifier callback works with binary images (e.g. NM). The new run() method accepts two Mat input parameters. One for the gray scale (or color) source image and the other for a binary mask where each connected component corresponds to a pre-segmented character in the input image. This way the OCRHMMDecoder is able to work with character classifiers that operate in grey scale (or color) images (e.g. a CNN).

Adds example on segmented word recognition. Shows the use of the OCRHMMDecoder with the NM and CNN default classifiers.

Minor bugfix: removes unwanted space character at the begining of recognition output strings.

Fix w64 warnings

Fix w64 warnings

Improving DisparityWLSFilter interface and adding a tutorial

Now the filter natively supports StereoBM and StereoSGBM with no
parameter tuning required. Also, now user won't need to set the ROI and
the right matcher parameters manually, it is all done in the respective
convenience factory method based on the left matcher instance. Tutorial
was added to clarify the provided example of use.

doc update